# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Windows Installer

on:
  workflow_run:
    workflows: ["Build and run tests (CI)"]
    branches: ["main"]
    types:
      - completed

jobs:
  build:
    # Run only if main workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    steps:
    - name: Download Wix
      uses: i3h/download-release-asset@v1
      with:
        owner: wixtoolset
        repo: wix3
        tag: wix3112rtm
        file: wix311-binaries.zip
    - name: Decompress Wix
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: wix311-binaries.zip
        pathTarget: ./target/wix
    - name: "Add Wix to Path"
      run: echo "$HOME/target/wix" >> $GITHUB_PATH
    - uses: actions/checkout@v2
    - name: "Set up JDK 16"
      uses: actions/setup-java@v1
      with:
        java-version: 16
        distribution: 'adopt'
    - name: "Modularize dependencies"
      run: ./build-modularized-version-of-dependencies.sh
      shell: bash
    - name: "Build with Maven"
      run: ./mvnw -B clean install -P mkinstaller
    - name: "Update Automatic Release"
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "Windows-latest"
        prerelease: false
        title: "Windows Development Build"
        files: ./gui/target/*.msi